# Generated by Django 5.1.2 on 2024-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_factor_year_car_factory_year_car_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField(verbose_name='Qtde de Carros')),
                ('cars_value', models.FloatField(verbose_name='Valor Total Carros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='cars/no-photo.jpg', upload_to='cars/', verbose_name='Foto'),
        ),
    ]
